version: "3.3"

services:
  # ===============
  # Proxy
  # ===============
  traefik:
    image: "traefik:latest"
    container_name: traefik
    hostname: traefik
    command:
      - --api
      - --certificatesresolvers.leresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory
      - --certificatesresolvers.leresolver.acme.email=mr.unlistedi@gmail.com #Set your email address here, is for the generation of SSL certificates with Let's Encrypt. 
      - --certificatesresolvers.leresolver.acme.httpchallenge.entrypoint=web
      - --certificatesresolvers.leresolver.acme.httpchallenge=true
      - --certificatesresolvers.leresolver.acme.storage=./acme.json
      - --certificatesresolvers.leresolver.acme.tlschallenge=true
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --log.level=ERROR
      - --providers.docker
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./traefik/acme.json:/acme.json"
    environment:
      - TZ=Asia/Makassar
    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik.entrypoints=websecure
      - traefik.http.routers.traefik.rule=Host(`traefik.myiot.com`)
      - traefik.http.routers.traefik.service=api@internal
      - traefik.http.routers.traefik.tls.certresolver=leresolver
      - traefik.http.routers.traefik.tls=true
      # Redirect HTTP -> HTTPS
      - traefik.http.routers.http-catchall.rule=hostregexp(`{host:.+}`)
      - traefik.http.routers.http-catchall.entrypoints=web
      - traefik.http.routers.http-catchall.middlewares=redirect-to-https
      - traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https
    networks:
      - services-proxy
      - services-db

  # ===============
  # Container Manager
  # ===============
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    command: -H unix:///var/run/docker.sock
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./portainer/data:/data
    labels:
      - traefik.enable=true
      - traefik.http.routers.portainer.entrypoints=websecure
      - traefik.http.routers.portainer.rule=Host(`portainer.myiot.com`)
      - traefik.http.routers.portainer.service=portainer
      - traefik.http.routers.portainer.tls.certresolver=leresolver
      - traefik.http.routers.portainer.tls=true
      - traefik.http.services.portainer.loadbalancer.server.port=9000
    environment:
      - TZ=Asia/Makassar
    networks:
      - services-proxy

  # ===============
  # Database
  # ===============
  mongodb:
    image: mongo:4.4.6
    container_name: mongodb
    hostname: mongodb
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./mongodb:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456
      TZ: Asia/Makassar
    networks:
      - services-db

  # ===============
  # DB Manager
  # ===============
  mongo-express:
    #port:8081
    image: mongo-express
    container_name: mongo-express
    hostname: mongo-express
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: 123456
      ME_CONFIG_MONGODB_URL: mongodb://root:123456@mongodb:27017/
      TZ: Asia/Makassar
    networks:
      - services-db
      - services-proxy
    labels:
      - traefik.enable=true
      - traefik.http.routers.mongo-express.entrypoints=websecure
      - traefik.http.routers.mongo-express.rule=Host(`db.myiot.com`)
      - traefik.http.routers.mongo-express.service=mongo-express
      - traefik.http.routers.mongo-express.tls.certresolver=leresolver
      - traefik.http.routers.mongo-express.tls=true
      - traefik.http.services.mongo-express.loadbalancer.server.port=8081
    depends_on:
      - mongodb

  # ===============
  # Services
  # ===============
  web-landing:
    image: python:3.10.6-slim-bullseye
    container_name: web-landing
    hostname: web-landing
    volumes:
      - ./services/landing:/usr/src/app
    environment:
      TZ: Asia/Makassar
    networks:
      - services-db
      - services-proxy
    working_dir: /usr/src/app
    command: /bin/bash -c "pip3 install -r requirements.txt && python app.py"
    labels:
      - traefik.enable=true
      - traefik.http.routers.web-landing.entrypoints=websecure
      - traefik.http.routers.web-landing.rule=Host(`myiot.com`)
      - traefik.http.routers.web-landing.service=web-landing
      - traefik.http.routers.web-landing.tls.certresolver=leresolver
      - traefik.http.routers.web-landing.tls=true
      - traefik.http.services.web-landing.loadbalancer.server.port=8080

  api-sensor:
    image: python:3.10.6-slim-bullseye
    container_name: api-sensor
    hostname: api-sensor
    volumes:
      - ./services/sensor:/usr/src/app
    environment:
      DB_HOSTNAME: mongodb
      DB_PORT: 27017
      DB_USERNAME: root
      DB_PASSWORD: 123456
      DB_NAME: myiot
      TZ: Asia/Makassar
    networks:
      - services-db
      - services-proxy
    working_dir: /usr/src/app
    command: /bin/bash -c "pip3 install -r requirements.txt && python app.py"
    labels:
      - traefik.enable=true
      - traefik.http.middlewares.web-sensor.stripprefix.forceslash=false
      - traefik.http.middlewares.web-sensor.stripprefix.prefixes=/sensor/,/sensor
      - traefik.http.routers.web-sensor.entrypoints=websecure
      - traefik.http.routers.web-sensor.middlewares=web-sensor
      - traefik.http.routers.web-sensor.rule=(Host(`api.myiot.com`) && (PathPrefix(`/sensor/`) || PathPrefix(`/sensor`)))
      - traefik.http.routers.web-sensor.service=web-sensor
      - traefik.http.routers.web-sensor.tls.certresolver=leresolver
      - traefik.http.routers.web-sensor.tls=true
      - traefik.http.services.web-sensor.loadbalancer.server.port=8080

  # ===============
  # DB Tester
  # ===============
  whoami:
    image: traefik/whoami
    container_name: whoami
    environment:
      TZ: Asia/Makassar
    labels:
      - traefik.enable=true
      - traefik.http.routers.whoami.entrypoints=websecure
      - traefik.http.routers.whoami.rule=(Host(`myiot.com`) && Path(`/whoami`))
      - traefik.http.routers.whoami.service=whoami
      - traefik.http.routers.whoami.tls.certresolver=leresolver
      - traefik.http.routers.whoami.tls=true
      - traefik.http.services.whoami.loadbalancer.server.port=80
    networks:
      - services-proxy

networks:
  services-proxy:
  services-db:


volumes:
  portainer_data:
